version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "Testexec123"
            ACCEPT_EULA: "Y"